server:
  port: 8701

spring:
  application:
    name: consumer-service
    
feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8601/eureka/