server:
  port: 8903

spring:
  application:
    name: lottery-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/account?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: admin

#mybatis-plus:
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  typeAliasesPackage: com.sf.lottery.bean #实体扫描，多个package用逗号或者分号分隔
  typeEnumsPackage: com.sf.lottery.enums
  configuration:
      map-underscore-to-camel-case: false
      cache-enabled: false
  global-config:
    id-type: 0 #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    field-strategy: 2 #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    db-column-underline: true #驼峰下划线转换
    refresh-mapper: true #刷新mapper 调试神器
    capital-mode: false #数据库大写下划线转换
    logic-delete-value: 0 #逻辑删除配置
    logic-not-delete-value: 1 #逻辑删除配置
#    meta-object-handler: com.baomidou.springboot.xxx #自定义填充策略接口实现
#    sql-injector: com.baomidou.springboot.xxx #自定义SQL注入器
#    key-generator: com.baomidou.springboot.xxx #序列接口实现类配置


eureka:
  client:
    service-url:
      defaultZone: http://admin:root@localhost:8601/eureka/
