server:
  port: 8801

spring:
  application:
    name: gateway-service

eureka:
  client:
    service-url:
      defaultZone: http://admin:root@localhost:8601/eureka/
      
zuul:
  routes:
    api-report:
      path: /api-report/**
      service-id: consumer-service