server:
  port: 8902

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:3306/account?useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 3
    min-idle: 5
    max-active: 10
    max-wait: 10000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    validation-query: select 1
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
  redis:
    host: 127.0.0.1
    port: 6379
    password: 
    timeout: 0
    pool:
      max-active: 10
      max-idle: 5
      min-idle: 3
      max-wait: -1

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  level:
    com.sf.account.dao: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://admin:root@localhost:8601/eureka/
